exp_name: !!str pipelinetest

# python train.py --config configs/small.yaml

checkpoint_dir: !!str ../checkpoints
#^X

result_dir: !!str results # currently not used revisit later
#^X


# specify model structure

backbone: !!str resnet-18

num_classes: !!int 2  #number of outputs of the model, only used for classification
#^X

# loss function parameters

class_weights: !!str 3,1 # the weight for each class, e.g. 3,1 for class 0:class 1 = 3:1
#==class-weights

outcome_type: !!str classification # choose between classification, survival, regression
#==outcome-type


# specify the path of the meta files

data_split: !!str /databig/POPPSlide/data_split4_noNAC_small.pickle # pickle dictionary with file paths under train/val/test split
#similar to test-meta, train-meta

# data_stats: !!str /databig/POPPSlide/data_stats.pickle # pickle dictionary
# mean, std, could be define here

data_stats_mean: [0.8523, 0.7994, 0.8636]
data_stats_std: [0.1414, 0.2197, 0.0854]

class_label: # self-defined label encoding
    nodepos: !!int 1
    nodeneg: !!int 0
#can be in other form

# specify patch manipulations

train_level: !!str slide # choice of slide/patient level
#^X

crop_size: !!int 224
#==crop-size

num_crops: !!int 1
#==num-crops

num_patches: !!int 16
#==num-patches

# learning rate
lr_backbone: !!float 1e-6

lr_head: !!float 1e-4

cosine_anneal_freq: !!int 100

cosine_t_mult: !!int 1



# specify experiment details

use_cuda: !!bool True
#^obsolete

mode: !!str train

patience: !!int 100

epochs: !!int 1

pretrain: !!bool True

random_seed: !!int 1234

resume: !!str  # path to resume model


# data specific arguments

batch_size: !!int 16

stratify: !!str status # only used for survival

sampling_ratio: !!str '3,1' # only used for survival problem

num_workers: !!int 1


# model regularization

dropout: !!float 0

wd_backbone: !!float 0.0001

wd_head: !!float 1e-5

l1: !!float 0

l2: !!float 0


# evaluation details
sample_id: !!bool False

num_val: !!int 128

val_batch_size: !!int 1
#^??

# model monitoring#

timestr: !!str  ## the name of the current experiment, will use current time if leave blank

log_freq: !!int 1

save_interval: !!int 5


# unused

outcome: !!str
